// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhpjlgsilivjrifsibqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRocGpsZ3NpbGl2anJpZnNpYnFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTk3MDYsImV4cCI6MjA2OTI5NTcwNn0.X1hi0DVTu2V5BRNZuEAUNObD_jCEM2k-sS09ldQuzm4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});