// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzclrozyrzevryphijqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6Y2xyb3p5cnpldnJ5cGhpanFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ0OTgzNjksImV4cCI6MjA4MDA3NDM2OX0.zsOeAZGh9-tWFZXLCqzcuFR-sJeDtAIB4zz7kJkGR5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
